### ISSUE TITLE
Application Libraries tracking.

### ISSUE THREAD

**Issue by Studzic** [Bootcamp-Group5/simply-unused#14]
Must use at least one new library, package, or technology that we haven’t discussed

**Comment by esroleo** [comment]
GIS tested.

**Comment by Uot-Project1-Group07** [comment]
"dependencies": {
    "bcrypt": "^5.0.1",
    "connect-session-sequelize": "^7.1.1",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "express-handlebars": "^5.2.1",
    "express-session": "^1.17.1",
    "food": "^0.3.5",
    "g-i-s": "^2.1.6",
    "handlebars": "^4.7.7",
    "mysql2": "^2.2.5",
    "sequelize": "^6.5.1"

**Comment by Bootcamp-Group5** [comment]
This issue is created as a reminder to create a library to host the user's information as well as what they add to their cart in the dashboard

**Comment by Studzic** [comment]
Handlebars have been completed
